#+TITLE: Running Specification Generator
#+Author: Pulkit
#+Date: [2017-04-06 THU]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil
* Introduction
  - This file includes the explanation of how to run the script to create lab and experiment specification files into a new format from the existing format.

** Setting up Dependencies
  - Install Python environment ver 2.7
  - Emacs editor can be used to make changes in the code

** Fetching existing Lab files (Old format including experiment details)
  - All the old existing lab files need to be cloned into your local machine from here: [[https://github.com/vlead/lab-specifications][old-lab-specs]].

** Running the Script
  - To run the script, we have two input requirements:
    + A folder containing the existing labs file cloned from the above step.
    + A new folder where the user wants to store the newly generated lab and experiment files.

  - Also keep in mind, the institute folder which the user want to modify, must not be present in the newly created empty folder, else the script will show an error while its execution. It will be automatically created with the script. If the folder is already present, then delete it and run the script again.


** Example Run of the Script
   - After installing and cloning all the necessary files, you need to run
     script as the below mentioned steps explains:
     + Change mode of the python script into executable mode by typing :

       #+BEGIN_EXAMPLE
       chmod +x file-name.py
       #+END_EXAMPLE

     * Run the script : 

       #+BEGIN_EXAMPLE
       ./file-name.py
       #+END_EXAMPLE
       
     + A message will appear stating : 

       #+BEGIN_EXAMPLE
       Welcome to Specification Creator 
       #+END_EXAMPLE
     
     + Now, you will be asked for the Old folder link and will get a message :

       #+BEGIN_EXAMPLE
       Enter old Path :
       #+END_EXAMPLE

     + Get the path entered for the folder which contains all the existing
       files cloned in step 3.  Make sure to enter the folder path institute
       wise, for e.g. for amrita university, you have to give path for amrita
       university as a whole and not for its individual labs After you will
       enter the path, you will get a message:

       #+BEGIN_EXAMPLE
       Enter New Path :
       #+END_EXAMPLE

     + Now you have to give the path of the new folder where you want to keep
       your newly created lab and experiment files.

     + Now you will be asked, whether you want only the labs specs or
       Experiment specs also. You will get a message :
       
       #+BEGIN_EXAMPLE
       Do you want Experiment Spec also ? 
       Type "Y" or "N" !!!
       #+END_EXAMPLE

     + Enter the choice as required and you will get a message for successful
       completion of the conversion.

     + You can the find the converted files at the defined new folder path

     + The process has to be repeated for converting the other institute spec
       also.

   
